### ISSUE TITLE
Issues with Expo 53 + new arch

### ISSUE THREAD

**Issue by Ashoat** [mattermost/react-native-paste-input#47]
While upgrading our app to Expo 53 + new arch, we've noticed some issues with version 0.8.1 this package (latest at this time).

On the iOS side we were seeing compilation failures due to changes from two upstream PRs:
* https://github.com/facebook/react-native/pull/47205
* https://github.com/facebook/react-native/pull/48133

Looking at the changes there, I was able to come up with this patch that made things compile again: https://gist.github.com/Ashoat/14a98badc16afc4ed297288a01a69f6e

On the Android side, I saw a runtime error when opening a `PasteInput`, which was fixed in #40. I was able to fix this by patching the same fix locally, but would be good if a release was published with the fix.

**Comment by Ashoat** [comment]
I've observed another issue, which is that on Android the height of a multiline input doesn't adjust.

Looks like @haileyok came up with a solution to that here: https://github.com/bluesky-social/react-native-paste-input/commit/1711caedf7e43bb305d397d218276de7d6a71ba7

EDIT – tried that solution, but didn't have any luck with it.

**Comment by haileyok** [comment]
@Ashoat I updated this to work with Expo 53/0.79. See https://github.com/mattermost/react-native-paste-input/pull/48. Think it addresses all of your issues.

**Comment by Ashoat** [comment]
@haileyok, you rock!!! Crazy impressive work. I tested it and it works 100% for me.

**Comment by Ashoat** [comment]
I've observed one more issue with this package on Expo 53 + new arch, which unfortunately is still present in @haileyok's PR.

This issue only applies on iOS, and only applies when using `children` instead of `value`.

The issue occurs when the user makes a typo while editing in the middle of an input.

| `children` (broken) | `value` |
| - | - |
| <video src="https://github.com/user-attachments/assets/81aba9ec-61ef-460e-8127-8f8ca09d3396" controls preload></video> | <video src="https://github.com/user-attachments/assets/7c978e14-bf5c-4b5e-b2ce-3ceaa70f7564" controls preload></video> |

Note that in the broken video using `children`, the autocorrect dropdown never appears, and when the autocorrect suggestion is automatically applied it mangles the text, placing the cursor in the middle of the correct word.

**Comment by johnjensenish** [comment]
Expo 54 (RN 0.81) is broken in new ways and unfortunately @haileyok's fork no longer compiles.

```ShadowNodes.cpp:52:31 No member named 'getEmptyPlaceholder' in 'facebook::react::BaseTextShadowNode'```

**Comment by enahum** [comment]
Main branch is now working on RN 0.83
